// Defining constants for actions and reducers

const RETRIEVE_SONG_LIST_SUCCESS = 'RETRIEVE_SONG_LIST_SUCCESS';
const RETRIEVE_SONG_REQUEST = 'RETRIEVE_SONG_REQUEST';
const CHANGE_SONG_REQUEST = 'CHANGE_SONG_REQUEST';
const NEXT_SONG_REQUEST = 'NEXT_SONG_REQUEST';

export default {
  RETRIEVE_SONG_LIST_SUCCESS,
  RETRIEVE_SONG_REQUEST,
  CHANGE_SONG_REQUEST,
  NEXT_SONG_REQUEST,
};
