// Defining constants for actions and reducers

const EDIT_PROFILE_REQUEST = 'LOG_IN_REQUEST';
const EDIT_PROFILE_SUCCESS = 'LOG_IN_SUCCESS';
const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR';
const SIGN_OUT_REQUEST = 'LOG_IN_REQUEST';
const SIGN_OUT_SUCCESS = 'LOG_IN_SUCCESS';
const SIGN_OUT_ERROR = 'LOG_IN_ERROR';
const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
const LOG_IN_ERROR = 'LOG_IN_ERROR';
const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';


export default {
  EDIT_PROFILE_REQUEST,
  EDIT_PROFILE_SUCCESS,
  EDIT_PROFILE_ERROR,
  SIGN_OUT_REQUEST,
  SIGN_OUT_SUCCESS,
  SIGN_OUT_ERROR,
  LOG_IN_REQUEST,
  LOG_IN_SUCCESS,
  LOG_IN_ERROR,
  SIGN_UP_REQUEST,
  SIGN_UP_SUCCESS,
  SIGN_UP_ERROR,
};

